# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LesTorfTravaImport
                                 A QGIS plugin
 Import data from  LTT DB
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-07-10
        copyright            : (C) 2020 by Aliaksei Andreyenka
        email                : alexey.andreenko@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LesTorfTravaImport class from file LesTorfTravaImport.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .LTT_import import LesTorfTravaImport
    return LesTorfTravaImport(iface)
